quarkus:
  application:
    name: rag-village
  jackson:
    accept-case-insensitive-enums: true
    serialization-inclusion: non-empty
  log:
    category:
      "dev.langchain4j":
        level: INFO
  http:
    port: 1337
  langchain4j:
    ollama:
      chat:
        log-requests: false
        log-responses: true
        chat-model:
          model-id: llama3.1:8b
          temperature: 0.7
      vision:
        log-requests: false
        log-responses: true
        chat-model:
          model-id: llava:latest
          temperature: 0.7
