package com.glycin.ragvillage.ai

import com.glycin.ragvillage.model.VillagerCommand
import dev.langchain4j.service.SystemMessage
import dev.langchain4j.service.UserMessage
import io.quarkiverse.langchain4j.RegisterAiService

@RegisterAiService(modelName = "chat", chatMemoryProviderSupplier = LimitedChatMemory::class)
interface CommandJudge {
    @SystemMessage("""
                You are a validation agent tasked with verifying the responses generated by a primary agent for a role-playing game set in Little Minas Morgul. 
                Your role is to extract structured data from the input you receive.
                                
                Your output must STRICTLY (I MEAN IT!) ADHERE TO THE FOLLOWING JSON FORMAT
                
                {
                  "moveTo": "string or null",
                  "talkTo": "string or null",
                  "wait": "boolean"
                }
                """)
    fun judgeCommand (@UserMessage messageToBeJudge: String) : VillagerCommand
}
